### ISSUE TITLE
 /usr/share/temboard-agent/auto_configure.sh : PGUSER & unexpected sudo

### ISSUE THREAD

**Issue by Krysztophe** [dalibo/temboard-agent#364] opened 2019-09-30 15:40 UTC
PGUSER is usually a database user. So when i setup this:
```
PGDATABASE=postgres
PGPORT=12001
PGUSER=temboard_agent
```
I expect the agent to connect on the database with the  `temboard_agent` PG user, not running itself with a `temboard_agent` system user, like it does:

```
root@monolithe:/etc/temboard-agent# cat /var/log/temboard-agent-auto-configure.log
++ readlink -m /usr/share/temboard-agent/auto_configure.sh/..
+ cd /usr/share/temboard-agent
+ ETCDIR=/etc/temboard-agent
+ VARDIR=/var/lib/temboard-agent
+ LOGDIR=/var/log/temboard-agent
+ export TEMBOARD_HOSTNAME=monolithe.christophecourtois.org
+ TEMBOARD_HOSTNAME=monolithe.christophecourtois.org
+ '[' -n '' ']'
...Sending monitoring data to https://monolithe:3001/.
+ setup_pq
+ export PGUSER=temboard_agent
+ PGUSER=temboard_agent
+ log 'Configuring for user temboard_agent.'
+ echo 'Configuring for user temboard_agent.'
+ tee -a /dev/fd/3
Configuring for user temboard_agent.
+ export PGDATABASE=postgres
+ PGDATABASE=postgres
+ export PGPORT=12001
+ PGPORT=12001
+ log 'Configuring for cluster on port 12001.'
+ echo 'Configuring for cluster on port 12001.'
+ tee -a /dev/fd/3
Configuring for cluster on port 12001.
+ export PGHOST=/var/run/postgresql
+ PGHOST=/var/run/postgresql
+ PGHOST=/var/run/postgresql

+ sudo -Eu temboard_agent psql -tc 'SELECT '\''Postgres connection working.'\'';'
sudo: utilisateur inconnu : temboard_agent
sudo: impossible d'initialiser le greffon de règles

+ fatal 'Can'\''t connect to Postgres cluster.'
+ echo -e '\e[1;31mCan'\''t connect to Postgres cluster.\e[0m'
```

Everything works ok if I create the agent without `PGPORT` (defaulting on `postgres`) and change  the user in `auto.conf` / `[postgresql]` / `user` and set `temboard_agent`.  (Of course, I've set up `pg_hba.conf` accordingly).

Using a separate system user would be a good idea but IMHO it should another parameter (in `[temboard]` section ?)

**Comment by bersace** [comment] 2019-11-05 14:19
I can't reproduce. Are you sure PGDATABASE is not set ?

cf. https://github.com/dalibo/temboard-agent/blob/master/share/auto_configure.sh#L115

**Comment by bersace** [comment] 2020-05-15 08:05
Fixed. Closing. If you have updates, please reopen.

**Closed by bersace** 2020-05-15 08:05 UTC
