### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by pmpetit** [dalibo/temboard-agent#207] opened 2018-05-15 08:11 UTC
Hello,
Simple test
docker-compose up -d
docker-compose exec agent bash
pip install -e /usr/local/src/temboard-agent/
sudo -u postgres temboard-agent

root@69af4d3c1dbe:/var/lib/temboard: pip install -e /usr/local/src/temboard-agent/
Obtaining file:///usr/local/src/temboard-agent
Installing collected packages: temboard-agent
  Found existing installation: temboard-agent 1.2
    Uninstalling temboard-agent-1.2:
      Successfully uninstalled temboard-agent-1.2
  Running setup.py develop for temboard-agent
Successfully installed temboard-agent

=> 
root@69af4d3c1dbe:/var/lib/temboard# sudo -u postgres temboard-agent
sudo: unknown user: postgres
sudo: unable to initialize policy plugin
root@69af4d3c1dbe:/var/lib/temboard# 

where is created user postgres ?

thanks

**Comment by bersace** [comment] 2018-05-15 08:14
Bonjour,

Docker image changed to match rpm installation. https://github.com/dalibo/temboard-agent/pull/206 Ensure you use the latest docker image with `docker pull dalibo/temboard-agent`.

**Comment by pmpetit** [comment] 2018-05-15 08:26
still have error : 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
TypeError: can't pickle _ssl._SSLSocket objects
ERROR: HTTP Error 500: Internal Server Error
ERROR: Traceback (most recent call last):
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/scheduler/taskmanager.py", line 809, in exec_worker
ERROR:     res = getattr(sys.modules[module], function)(*args, **kws)
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/scripts/agent.py", line 99, in wrapper
ERROR:     return function(app=self.app, *a, **kw)
ERROR:   File "/usr/local/src/temboard-agent/temboardagent/plugins/monitoring/__init__.py", line 214, in monitoring_sender_worker
ERROR:     raise e
ERROR: HTTPError: HTTP Error 500: Internal Server Error
 INFO: Loaded probe: locks

**Comment by pmpetit** [comment] 2018-05-15 08:30
other question : 
in the docker-compose 
  agent:
    image: dalibo/temboard-agent
so i get the agent from the repo.

how can i do to modify it ? 
every time i execute the docker-compose it will use the repo's image ?

**Comment by bersace** [comment] 2018-05-15 08:32
There is two errors. The first looks like a bug :

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/multiprocessing/queues.py", line 268, in _feed
    send(obj)
TypeError: can't pickle _ssl._SSLSocket objects
```

Can you enable debug logs (you can just edit and send kill -HUP to enable debug logs without restarting).

The 500 internal error is detail in UI logs.

**Comment by bersace** [comment] 2018-05-15 08:33
@pmpetit Yes, the docker-compose.yml file tells to pull `dalibo/temboard-agent` image for docker Hub.

@pmpetit What do you want to modify ?

You may find some help on docker-compose in official documentation : https://docs.docker.com/compose/extends/ .

**Comment by pmpetit** [comment] 2018-05-15 08:40
about the bug : 
1/ when the agent is registered in the ui, then the error is not raised anymore
2/ i do not understand (you can just edit and send kill -HUP to enable debug logs without restarting)

**Comment by bersace** [comment] 2018-05-15 08:48
>  For example, i'd like to add a chart to the dashboard from a personal query.

That's a nice feature you're asking to.

At the moment, a solution would be to :

1. add a new endpoint in agent via a plugin.
2. fork the dashboard plugin in UI to add a chart using the new endpoint.

cc @julmon @pgiraud

**Comment by pmpetit** [comment] 2018-05-15 09:30
for training, could you please tell me where is the query that shows the Transactions Per Second,
it will help me to understand how you manage the elapsed time and the whole process.
Thanks

**Comment by bersace** [comment] 2018-05-15 09:32
cc @julmon

**Comment by bersace** [comment] 2018-05-15 09:48
@pmpetit : it's here

https://github.com/dalibo/temboard-agent/blob/master/temboardagent/plugins/dashboard/metrics.py#L176-L198

**Comment by pmpetit** [comment] 2018-05-15 15:44
using postgres user is ok, but
```
root@33608d90ef24:/var/lib/temboard-agent# sudo -u postgres temboard-agent-register --host $TEMBOARD_REGISTER_HOST --port $TEMBOARD_REGISTER_PORT --groups default $TEMBOARD_UI_URL
Getting system & PostgreSQL informations from the agent (https://0.0.0.0:2345/discover) ...
Login at https://172.17.0.1:8888 ...
 Username: admin
 Password: 
Registering instance/agent to https://172.17.0.1:8888 ...
CRITI: HTTP Error 401: Unauthorized
root@33608d90ef24:/var/lib/temboard-agent# 


```

**Comment by bersace** [comment] 2018-05-16 07:09
@pmpetit yes, it's outdated. I'm gonna fix this. Thanks !

**Comment by pmpetit** [comment] 2018-05-16 07:16
but there is still CRITI: HTTP Error 401: Unauthorized while registering
root@33608d90ef24:/var/lib/temboard-agent# sudo -u postgres temboard-agent-register --host $TEMBOARD_REGISTER_HOST --port $TEMBOARD_REGISTER_PORT --groups default $TEMBOARD_UI_URL
Getting system & PostgreSQL informations from the agent (https://0.0.0.0:2345/discover) ...
Login at https://172.17.0.1:8888 ...
 Username: admin
 Password: 
Registering instance/agent to https://172.17.0.1:8888 ...
CRITI: HTTP Error 401: Unauthorized

**Comment by pmpetit** [comment] 2018-05-16 08:10
the docker-agent env : 
```
root@3217aed15537:/var/lib/temboard-agent# env
TEMBOARD_SSL_KEY=/usr/local/src/temboard-agent/share/temboard-agent_CHANGEME.key
HOSTNAME=3217aed15537
GPG_KEY=C01E1CAD5EA2C4F0B8E3571504C367C218ADD4FF
TERM=xterm
TEMBOARD_KEY=key_for_agent0
PYTHONIOENCODING=UTF-8
PYTHON_VERSION=2.7.15
TEMBOARD_UI_URL=https://172.17.0.1:8888
TEMBOARD_GROUPS=default
PATH=/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/var/lib/temboard-agent
TEMBOARD_REGISTER_HOST=0.0.0.0
LANG=C.UTF-8
TEMBOARD_REGISTER_PORT=2345
PYTHON_PIP_VERSION=10.0.1
SHLVL=1
HOME=/root
TEMBOARD_HOSTNAME=repository.fqdn
TEMBOARD_SSL_CERT=/usr/local/src/temboard-agent/share/temboard-agent_CHANGEME.pem
affinity:container==33608d90ef249ad782bd056693cff94ece0f329345e890a4a75c7abd29e0c0be
TEMBOARD_SSL_CA=/usr/local/src/temboard-agent/share/temboard-agent_ca_certs_CHANGEME.pem
_=/usr/bin/env

```

**Comment by pmpetit** [comment] 2018-05-16 08:35
it seems the pb comes from the UI temboard_CHANGEME.*  grants files
they belongs to user  : myself
group Docker

**Comment by bersace** [comment] 2018-05-16 09:06
@pmpetit it looks like the credentials are either wrongs or there is a bug in UI. I don't think it's related to agent.

**Comment by pmpetit** [comment] 2018-05-16 09:10
here is the box when i click "new instance" in the UI (loggued as admin/admin)
![image](https://user-images.githubusercontent.com/4059185/40107809-8a7584ee-58f9-11e8-90ad-a644b4adf223.png)
and the log from the UI:
```
 INFO: 200 POST /monitoring/collector (172.19.0.4) 59.59ms
 INFO: 200 POST /monitoring/collector (172.19.0.4) 37.71ms
 INFO: 200 POST /monitoring/collector (172.19.0.4) 49.46ms
 INFO: Getting group list.
ERROR: Unauthorized access.
ERROR: Traceback (most recent call last):
ERROR:   File "/home/Z50PPETI/gitHome/temboard_project/temboard/temboardui/handlers/base.py", line 130, in func_wrapper
ERROR:     return func(self, *args, **kwargs)
ERROR:   File "/home/Z50PPETI/gitHome/temboard_project/temboard/temboardui/handlers/settings/group.py", line 33, in get_all
ERROR:     self.check_admin()
ERROR:   File "/home/Z50PPETI/gitHome/temboard_project/temboard/temboardui/handlers/base.py", line 50, in check_admin
ERROR:     raise TemboardUIError(401, "Unauthorized access.")
ERROR: TemboardUIError: Unauthorized access.
 INFO: Failed.
 INFO: 401 GET /json/settings/all/group/instance (127.0.0.1) 3.50ms
 INFO: 200 POST /monitoring/collector (172.19.0.4) 38.10ms
 INFO: 200 POST /monitoring/collector (172.19.0.4) 50.34ms


```

**Comment by julmon** [comment] 2018-05-16 09:12
@pmpetit it seems that your `admin` user (UI) is not flagged as administrator

**Comment by pmpetit** [comment] 2018-05-16 09:18
![image](https://user-images.githubusercontent.com/4059185/40108327-e02b332e-58fa-11e8-8afa-701c71faba4b.png)

**Comment by pmpetit** [comment] 2018-05-16 09:19
![image](https://user-images.githubusercontent.com/4059185/40108365-f2522a8a-58fa-11e8-8464-0dad70241ba0.png)

**Comment by pmpetit** [comment] 2018-05-16 15:05
When this PR is merged ?
When can i pull ?

**Comment by julmon** [comment] 2018-05-16 15:07
This PR has been merged into master.

**Comment by pmpetit** [comment] 2018-05-17 06:47
Hello,
you did not change in the https://github.com/dalibo/temboard/blob/master/CONTRIBUTING.md
for the user postgres instead of temboard....

**Comment by bersace** [comment] 2018-06-06 13:10
@pmpetit any update on this issue ?

**Comment by pgiraud** [comment] 2018-06-07 08:40
@pmpetit I need an update on this topic.
Can you please tell what you are trying to do?
It looks like you are following the `CONTRIBUTING.md` instructions. Are you also trying to launch your own agent? Are you planning to write code for the agent?  *see "working on the agent at the same time" section*
If not you should probably get rid of the docker-compose overriden config and rely on the agent provided by default.

For your information the `Authentication cookie is missing` is not critical and will appear each time the user tries to access to a section is not allowed to view because of a lack of credentials. The application should in this case automatically redirect the user to a login form. Either the global one (`/login`) or the agent specific one (`/server/0.0.0.0/2345/login`). In both cases, the error appears even when the application works correctly. It's the intended behavior.

In any case, if you still have problems can you please elaborate what "I can not log on" means? And provide the detailed procedure you are following?
I would be happy to help as much as I can and make the contribution as straight forward as possible.

**Comment by pmpetit** [comment] 2018-06-07 08:49
Hello,
i ma just trying to follow "https://github.com/dalibo/temboard/blob/master/CONTRIBUTING.md" with the docker container.

Everything is running well, except i can not logon to temboard => Authentication cookie is missing
and i can not get into temboard.

**Comment by pmpetit** [comment] 2018-06-07 09:06
do you want me to do again the whole procedure and send you several screenshots ?

**Comment by pgiraud** [comment] 2018-06-07 09:09
Please do. It will be helpful. We can also do it outside github to avoid noise.
Please send me the details at `pierre (dot) giraud (at) dalibo (dot) com` (en français).

**Closed** 2018-06-07 13:48 UTC
