### ISSUE TITLE
Cannot add user with temboard-agent-adduser

### ISSUE THREAD

**Issue by Mika313** [dalibo/temboard-agent#512] opened 2021-01-06 22:50 UTC
Hello,

When i run the command
`temboard-agent-adduser -c /etc/temboard-agent/<appli>/temboard-agent.conf`
i have the error below:
` INFO: Starting temboard-agent-adduser 7.3.`
`ERROR: Invalid postgresql_host from config: Not a directory...`
`CRITI: Failed to load configuration.`

I could not have more precisions.
I add `--debug` option but it does not display more logs.

temboard-agent version is 7.3

This is my config file:
`cat /etc/temboard-agent/appli/temboard-agent.conf`
`[temboard]`
home = /var/lib/temboard-agent-appli
hostname = dns.db.server
port = 2345
ssl_cert_file = /etc/pki/tls/certs/temboard-agent-appli.pem
ssl_key_file = /etc/pki/tls/private/temboard-agent-appli.key
key = acaf4axy0fre2d200edc4e9949c03aa15

`[logging]`
method = file
destination = /var/log/temboard-agent-appli. log

`[postgresql]`
host = /var/run/postgresql
port = 54325
user = superuser
dbname = db
instance = appli

`[administration]`
pg_ctl = '/usr/pgsql-11/bin/pg_ctl %s -D /data/pg_data'

Can you please tell me what is wrong ?
Thanks and Regards

**Comment by Mika313** [comment] 2021-01-15 19:28
Yes it does and it is an absolute path.
I changed
```
/etc/temboard/appli/temboard-agent.conf.d/auto.conf
/var/lib/temboard-agent/appli
/etc/temboard-agent/users
/var/log/temboard-agent/
```
owner to temboard UNIX user and it fix it.
I did not understand why several config files are taken into account by the `temboard-add-user` command and the `temboard-agent@.service` as well.
I am a little confused to configure the agent.

Many thanks.

**Comment by dlax** [comment] 2021-01-18 07:56
> Yes it does and it is an absolute path.

Can you run the following command and report the output here?
```
$ python3 -c 'import os.path; print(os.path.isdir("/var/run/postgresql"))'
```

**Comment by Mika313** [comment] 2021-01-18 09:28
> Can you run the following command and report the output here?

`python3 -c 'import os.path; print(os.path.isdir("/var/run/postgresql"))'`
True

**Comment by dlax** [comment] 2021-01-18 10:48
Ok; then I have no idea what's wrong here. Sorry.

**Comment by Mika313** [comment] 2021-01-19 07:44
Hello @dlax,
As i said, changing `/etc/temboard/appli/temboard-agent.conf.d/auto.conf` permission fixed the issue. 
But i do not know why `auto.conf` file was took into account by the command `temboard-agent-adduser -c /etc/temboard-agent/<appli>/temboard-agent.conf`

**Comment by dlax** [comment] 2021-01-19 08:09
> But i do not know why `auto.conf` file was took into account by the command `temboard-agent-adduser -c /etc/temboard-agent/<appli>/temboard-agent.conf`

This is documented:

"temBoard agent always searches for a directory whose name is built with 
the config file and the .d suffix."

https://temboard-agent.readthedocs.io/en/v7/configuration.html

(Still, I fail to see the link with the initial error message.)

**Comment by Mika313** [comment] 2021-01-19 08:52
> (Still, I fail to see the link with the initial error message.)

Sorry @dlax you are right. I did not explain the link.

After running `auto_configure.sh` script, `host` parameter was set to the database DNS (maybe taken from `$TEMBOARD_HOSTNAME` or `$PGHOST`).
Then, i only updated `/etc/temboard-agent/<appli>/temboard-agent.conf` file setting `host` parameter to UNIX socket directory `/var/run/postgresql`.
But wrongly, i did not updated `/etc/temboard-agent/<appli>/temboard-agent.conf.d/auto.conf` file which has `host` parameter still set to the database DNS.

So the complete explanation is :
i updated `/etc/temboard-agent/<appli>/temboard-agent.conf.d/auto.conf` file
and i set correct permissions and ownership of the files below
```
/etc/temboard/appli/temboard-agent.conf.d/auto.conf
/var/lib/temboard-agent/appli
/etc/temboard-agent/users
/var/log/temboard-agent/
```

> This is documented:
>
> "temBoard agent always searches for a directory whose name is built with
> the config file and the .d suffix."

Maybe it would be clearer to precise something like this:
"temBoard agent always searches for a directory whose name is built with the config file and the .d suffix" _even if temboard-agent -c points to another configuration file_.  
If i understand, the idea is to precise that when you run `temboard-agent` with `-c` option pointing to a specific file, it is not exclusive. And maybe add configuration file precedence.
It is only my humble opinion ; )

Many Thanks.

**Comment by dlax** [comment] 2021-01-19 09:20
> So the complete explanation is :
> i updated `/etc/temboard-agent/<appli>/temboard-agent.conf.d/auto.conf` file
> and i set correct permissions and ownership of the files below

Ok, I see. So the problem is resolved I guess. I'll close this issue then. 

> > This is documented:
> > "temBoard agent always searches for a directory whose name is built with
> > the config file and the .d suffix."
> 
> Maybe it would be clearer to precise something like this:
> "temBoard agent always searches for a directory whose name is built with the config file and the .d suffix" _even if temboard-agent -c points to another configuration file_.
> If i understand, the idea is to precise that when you run `temboard-agent` with `-c` option pointing to a specific file, it is not exclusive. And maybe add configuration file precedence.
> It is only my humble opinion ; )

I agree, that's quite counter-intuitive. (I came after this system got designed, so I'm perhaps missing a bit context.)
Anyway, if you feel like the documentation could be improved in some way, submit a PR!

**Closed by dlax** 2021-01-19 09:20 UTC
